import type { CustomLevelData } from "../level";

/**
 * Compact source-owned course exercising every reusable primitive introduced
 * by the Unity gameplay backport. It is intentionally readable greybox: each
 * station has enough recovery floor to verify behavior without editing data.
 */
export const BACKPORT_LAB_LEVEL: CustomLevelData = {
  v: 1,
  name: "Backport Mechanics Lab",
  spawn: [0, 0.12, 16],
  killY: -12,
  sky: "day",
  groups: [
    { id: 1, nm: "start and speed" },
    { id: 2, nm: "wood and bamboo" },
    { id: 3, nm: "air trick gates" },
    { id: 4, nm: "portal recovery" },
    { id: 5, nm: "camera" },
  ],
  components: [
    {
      t: "platform",
      p: [0, -0.5, 12],
      s: [14, 1, 20],
      tex: "pavement",
      color: "#7f8d92",
      grp: 1,
    },
    {
      t: "speedpad",
      p: [0, 0, 5],
      s: [4, 0.3, 5],
      speed: 48,
      cycle: 3.9,
      grp: 1,
    },
    {
      t: "woodpath",
      p: [0, 0, 3],
      w: 6,
      curve: "spline",
      scaffold: true,
      supports: true,
      rails: true,
      spacing: 0.55,
      baySpacing: 3.8,
      supportDepth: 3.5,
      color: "#8b5a2b",
      tex: "plank",
      seed: 7319,
      pts: [
        [0, 0, 0, 0, 0],
        [2.5, -14, 0, 1, 4],
        [-2, -29, 0, 2.8, -5],
        [0, -45, 0, 0, 0],
      ],
      widths: [6, 6.8, 5.4, 6.2],
      grp: 2,
    },
    {
      t: "trampoline",
      p: [0, 0, -47],
      s: [5, 0.45, 5],
      speed: 16,
      amp: 1.25,
      grp: 3,
    },
    {
      t: "platform",
      p: [0, -0.5, -61],
      s: [16, 1, 20],
      tex: "checker",
      color: "#75828c",
      grp: 3,
    },
    {
      t: "trickgate",
      p: [0, 4, -55],
      s: [14, 10, 0.6],
      radius: 2.2,
      trick: "kick",
      yaw: 0,
      nm: "Kickflip gate",
      grp: 3,
    },
    {
      t: "trickrail",
      p: [4.2, 1, -64],
      len: 14,
      yaw: 0,
      trick: "heel",
      nm: "Heelflip rail",
      grp: 3,
    },
    { t: "checkpoint", p: [-4, 0.5, -68], grp: 3 },
    {
      t: "platform",
      p: [0, -0.5, -86],
      s: [18, 1, 24],
      tex: "stone",
      color: "#71817a",
      grp: 4,
    },
    {
      t: "grindosaurus",
      p: [0, 0, -78],
      range: 3,
      speed: 1.5,
      coverage: 0.65,
      yaw: 0,
      nm: "moving spine grind",
      grp: 4,
    },
    {
      t: "vertramp",
      p: [0, 0, -91],
      len: 10,
      rise: 4.6,
      w: 3,
      vkind: "half",
      grp: 4,
    },
    {
      t: "angryball",
      p: [0, 0, -91],
      w: 3,
      rise: 4.6,
      radius: 0.8,
      range: 12,
      speed: 7,
      yaw: 0,
      grp: 4,
    },
    {
      t: "returnportal",
      p: [8, 0, -106],
      s: [3, 4, 1.2],
      to: [0, 0.2, -70],
      exitYaw: 0,
      airOnly: false,
      nm: "recovery portal",
      grp: 4,
    },
    {
      t: "platform",
      p: [0, -0.5, -121],
      s: [16, 1, 14],
      tex: "pavement",
      color: "#778790",
      grp: 4,
    },
    { t: "gate", p: [0, 0, -124], grp: 4 },
    { t: "clock", p: [2.8, 0, 12], grp: 1 },
    { t: "comboorb", p: [-2.8, 0, 12], grp: 1 },
    { t: "camnode", p: [0, 2, 18], radius: 5, grp: 5 },
    { t: "camnode", p: [0, 2, -4], radius: 7, grp: 5 },
    { t: "camnode", p: [0, 3, -35], radius: 8, grp: 5 },
    { t: "camnode", p: [0, 2, -68], radius: 7, grp: 5 },
    { t: "camnode", p: [0, 2, -126], radius: 4, grp: 5 },
  ],
};
