"""Blender: fit individual Meshy blocks to documented units and build a real LOD.

Run Blender --background --python tools/jungle-kit/bake_modular.py -- [names].
No scene/building geometry is generated by this script; every part is one
downloaded Meshy model. The dimensions, seating planes, normals and LOD are
the reusable module contract that the authored level assembly relies on.
"""
import bpy
import bmesh
import json
import math
import os
import sys
import argparse
from pathlib import Path
from mathutils import Matrix, Vector
from mathutils.geometry import intersect_ray_tri

ROOT = Path(__file__).resolve().parents[2]
WORK = Path(os.environ.get('JUNGLE_ASSET_WORK', ROOT / '.img2threejs/jungle-kit'))
OUT = WORK / 'modular-baked'
OUT.mkdir(parents=True, exist_ok=True)
parser = argparse.ArgumentParser()
parser.add_argument('--spec', default='tools/jungle-kit/module-specs.json')
parser.add_argument('names', nargs='*')
args = parser.parse_args(sys.argv[sys.argv.index('--')+1:] if '--' in sys.argv else [])
specs = json.loads((ROOT/args.spec).read_text())
if args.names: specs = [s for s in specs if s['file'] in args.names]
report = []
flat_top = {'ashlar-clean','ashlar','broken-ashlar','paving-slab','column-base','column-shaft','column-capital','cornice','corner-cornice','lintel','temple-stair'}

for spec in specs:
    name = spec['file']
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete(use_global=False)
    bpy.ops.import_scene.gltf(filepath=str(WORK/spec.get('sourceFile',name+'.glb')))
    meshes = [o for o in bpy.context.scene.objects if o.type == 'MESH']
    for o in bpy.context.scene.objects: o.select_set(o in meshes)
    bpy.context.view_layer.objects.active = meshes[0]
    if len(meshes) > 1: bpy.ops.object.join()
    obj = bpy.context.view_layer.objects.active
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    mesh = obj.data
    coords = [v.co.copy() for v in mesh.vertices]
    lo = Vector(tuple(min(v[i] for v in coords) for i in range(3)))
    hi = Vector(tuple(max(v[i] for v in coords) for i in range(3)))
    span = hi-lo
    # Blender is Z-up; the exported GLB will return to Y-up.
    size = Vector((spec['size'][0], spec['size'][2], spec['size'][1]))
    center = Vector(((lo.x+hi.x)/2, (lo.y+hi.y)/2, lo.z))
    for v in mesh.vertices:
        v.co = Vector(tuple((v.co[i]-center[i])*size[i]/span[i] for i in range(3)))
        if v.co.z < size.z * 0.035: v.co.z = 0
        if name in flat_top and v.co.z > size.z * 0.965: v.co.z = size.z
        if name == 'arch-stone':
            t=max(0,min(1,v.co.z/size.z))
            v.co.x *= (.855+.145*t)/(.714+.286*t)
    if name == 'roof-hip':
        # Meshy interpreted the reference as a complete small pyramid. A
        # height-dependent shear moves its peak to the inside corner, making
        # the two outer roof planes meet the straight modules correctly.
        high=[v.co for v in mesh.vertices if v.co.z>size.z*.9]
        peak=Vector((sum(v.x for v in high)/len(high),sum(v.y for v in high)/len(high),size.z))
        for v in mesh.vertices:
            t=max(0,min(1,(v.co.z-size.z*.2)/(size.z*.8)))
            v.co.x=max(-size.x/2,v.co.x+(-size.x/2-peak.x)*t)
            v.co.y=min(size.y/2,v.co.y+(size.y/2-peak.y)*t)
    if name in {'roof-wedge','roof-hip'}:
        bm=bmesh.new();bm.from_mesh(mesh)
        bmesh.ops.remove_doubles(bm,verts=list(bm.verts),dist=0.00001)
        bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces))
        if name == 'roof-wedge':
            # The generated panel contained coplanar backing triangles with
            # opposite winding, plus a second surface just underneath it.
            # A roof block is a height field here: retain the outer surface.
            bm.faces.ensure_lookup_table()
            fronts=[f for f in bm.faces if f.normal.z>.2 and len(f.verts)==3]
            remove=[]
            for face in list(bm.faces):
                center=face.calc_center_median()
                if center.z<size.z*.12 or abs(center.x)>size.x*.46 or abs(center.y)>size.y*.46:continue
                for other in fronts:
                    if other==face:continue
                    hit=intersect_ray_tri(*(v.co for v in other.verts),Vector((0,0,-1)),Vector((center.x,center.y,size.z+1)),True)
                    if hit is None:continue
                    delta=hit.z-center.z
                    if (face.normal.z<-.2 and abs(delta)<.03) or (face.normal.z>.2 and .00001<delta<.04) or (face.normal.z>.2 and abs(delta)<.00001 and face.index>other.index):
                        remove.append(face);break
            bmesh.ops.delete(bm,geom=remove,context='FACES')
            print('Removed overlapping roof faces',len(remove),flush=True)
            bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces))
        bm.to_mesh(mesh);bm.free()
    mesh.update()
    # Smooth the broad bevels while keeping the main planes and large fractures.
    for face in mesh.polygons: face.use_smooth = True
    if hasattr(mesh, 'set_sharp_from_angle'): mesh.set_sharp_from_angle(angle=math.radians(42))
    if hasattr(mesh, 'use_auto_smooth'): mesh.use_auto_smooth = True
    normal = obj.modifiers.new('Face-weighted bevel normals', 'WEIGHTED_NORMAL')
    normal.keep_sharp = True
    normal.weight = 50
    bpy.ops.object.modifier_apply(modifier=normal.name)
    obj.name = name + '_LOD0'
    low = obj.copy()
    low.data = obj.data.copy()
    low.name = name + '_LOD1'
    bpy.context.collection.objects.link(low)
    bpy.context.view_layer.objects.active = low
    decimate = low.modifiers.new('Distant silhouette', 'DECIMATE')
    decimate.ratio = spec['lod']
    decimate.use_collapse_triangulate = True
    bpy.ops.object.modifier_apply(modifier=decimate.name)
    for o in bpy.context.scene.objects: o.select_set(o in (obj,low))
    bpy.context.view_layer.objects.active = obj
    bpy.ops.export_scene.gltf(filepath=str(OUT/(name+'.glb')), export_format='GLB',
        use_selection=True, export_yup=True, export_apply=True, export_materials='EXPORT',
        export_animations=False, export_cameras=False, export_lights=False)
    obj.data.calc_loop_triangles(); low.data.calc_loop_triangles()
    row = {'file':name, 'size':spec['size'], 'triangles':len(obj.data.loop_triangles), 'lodTriangles':len(low.data.loop_triangles)}
    report.append(row)
    print('MODULE',json.dumps(row),flush=True)
    for collection in [bpy.data.images,bpy.data.materials,bpy.data.meshes]:
        for block in list(collection):
            if block.users == 0: collection.remove(block)

(OUT/'bake-report.json').write_text(json.dumps(report,indent=2)+'\n')
