"""Pack the optional Meshy studies without replacing the level's original stone kit."""
import json
import pack_modular as shared

ROOT=shared.ROOT
shared.OUT=ROOT/'public/jungle-kit/editor'
shared.OUT.mkdir(parents=True,exist_ok=True)
specs=json.loads((ROOT/'tools/jungle-kit/editor-specs.json').read_text())
report=[shared.pack(spec) for spec in specs]
(shared.OUT/'manifest.json').write_text(json.dumps(report,indent=2)+'\n')
lines=['// Generated by tools/jungle-kit/pack_editor_assets.py.', 'export const JUNGLE_EDITOR_ASSETS = {']
for spec in specs:
    asset={'file':'editor/'+spec['file'],'label':spec['label'],'size':spec['size'],
        'wind':False,'normalStrength':spec['normal'],'lod':True}
    lines.append('  '+spec['kind']+': '+json.dumps(asset,separators=(',',':'))+',')
lines.extend(['} as const;',''])
(ROOT/'src/jungleEditorAssets.ts').write_text('\n'.join(lines))
print(json.dumps(report,indent=2))
