import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
const{chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const root=new URL('../../',import.meta.url),out=new URL('public/hud/balance-v1/',root);await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'});
try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5178/tools/balance-meter/bake.html');await page.waitForFunction(()=>window.balanceBake);
 const result=await page.evaluate(()=>window.balanceBake()),assets={frames:[],glove:null},provenance={generator:'built-in image_gen',sources:[],prompts:{}};
 for(const [i,f]of [...result.frames,result.glove].entries()){
  const file=i<4?`meter-${i}.png`:'glove.png';await fs.writeFile(new URL(file,out),Buffer.from(f.png.split(',')[1],'base64'));
  if(i<4)assets.frames.push({file:'hud/balance-v1/'+file,points:f.points});else assets.glove={file:'hud/balance-v1/'+file,tip:f.tip};
  const raw=await fs.readFile(new URL('art/balance-meter/v1/'+f.source,root));delete f.png;provenance.sources.push({...f,file,sha256:createHash('sha256').update(raw).digest('hex')});
 }
 const promptDir=new URL('art/balance-meter/v1/prompts/',root);for(const name of await fs.readdir(promptDir))provenance.prompts[name]=await fs.readFile(new URL(name,promptDir),'utf8');
 await fs.writeFile(new URL('src/balanceMeterAssets.ts',root),'// Generated by tools/balance-meter/bake.mjs from original image-model artwork.\nexport const BALANCE_METER_ASSETS = '+JSON.stringify(assets)+' as const;\n');
 await fs.writeFile(new URL('provenance.json',out),JSON.stringify(provenance,null,2)+'\n');
 if(errors.length)throw new Error(errors.join('\n'));console.log(JSON.stringify({frames:assets.frames.length,glove:assets.glove,errors}));
}finally{await browser.close();}
