import { readFile, readdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('../../desktop/release/', import.meta.url));
const names = (await readdir(root)).filter(name => /\.(?:dmg|zip|exe|AppImage|tar\.gz)$/.test(name)).sort();
if (!names.length) throw new Error('No distributable artifacts found');
const lines = [];
const targetArch = process.env.BONEMAN_TARGET_ARCH || process.arch;
for (const name of names) lines.push(createHash('sha256').update(await readFile(path.join(root, name))).digest('hex') + '  ' + name);
await writeFile(path.join(root, 'SHA256SUMS-' + process.platform + '-' + targetArch + '.txt'), lines.join('\n') + '\n');
console.log(lines.join('\n'));
