"""Share and compress city albedos; retain the pack's UVs and detailed meshes."""
import json,hashlib,subprocess,shutil,struct
from pathlib import Path
from PIL import Image
ROOT=Path(__file__).resolve().parents[2];WORK=ROOT/'.img2threejs/carlisle-coast/city-baked';OUT=ROOT/'public/carlisle-kit';TEX=OUT/'textures';TEX.mkdir(parents=True,exist_ok=True)
MODEL=WORK/'compressed'
doc=json.loads((MODEL/'city.gltf').read_text())
# Keep painted material detail and subdued normals for polished stylized game art.
for mat in doc['materials']:
    mat.pop('occlusionTexture',None)
    pbr=mat.setdefault('pbrMetallicRoughness',{});pbr.pop('metallicRoughnessTexture',None);pbr['metallicFactor']=0;pbr['roughnessFactor']=.86
colors={mat['pbrMetallicRoughness']['baseColorTexture']['index'] for mat in doc['materials'] if 'baseColorTexture' in mat.get('pbrMetallicRoughness',{})}
normals={mat['normalTexture']['index'] for mat in doc['materials'] if 'normalTexture' in mat}
used=colors|normals
previous={r['sourceSha256']:r for r in json.loads((TEX/'manifest.json').read_text())} if (TEX/'manifest.json').exists() else {}
image_map={};texture_map={};images=[];textures=[];report=[]
for tid in sorted(used):
    texture=doc['textures'][tid];im=doc['images'][texture['source']];source=MODEL/im['uri'];digest=hashlib.sha256(source.read_bytes()).hexdigest()
    if digest not in image_map:
        image=Image.open(source);alpha=image.mode=='RGBA' and image.getextrema()[3]!=(255,255)
        image=image.convert('RGBA' if alpha else 'RGB');image.thumbnail((2048,2048) if tid in colors else (512,512),Image.Resampling.LANCZOS)
        name=source.stem;png=TEX/(name+'-source.png');ktx=TEX/(name+'.ktx2');image.save(png)
        stamp=ktx.with_suffix('.source-hash')
        if not ktx.exists() or digest not in previous:
            subprocess.run(['/tmp/carlisle-ktx-runtime/bin/toktx','--t2','--encode','etc1s','--qlevel','220','--clevel','3','--threads','2','--genmipmap','--assign_oetf','srgb' if tid in colors else 'linear',str(ktx),str(png)],check=True,capture_output=True)
            stamp.write_text(digest)
        fallback=image.copy();fallback.thumbnail((1024,1024),Image.Resampling.LANCZOS)
        suffix='.png' if alpha else '.jpg';fp=TEX/(name+suffix)
        fallback.save(fp,**({'optimize':True} if alpha else {'quality':92,'optimize':True,'subsampling':0}))
        png.unlink();stamp.unlink(missing_ok=True)
        low=len(images);images.append({'name':name+' fallback','uri':'textures/'+fp.name,'mimeType':'image/png' if alpha else 'image/jpeg'})
        high=len(images);images.append({'name':name+' GPU','uri':'textures/'+ktx.name,'mimeType':'image/ktx2'})
        image_map[digest]=(low,high)
        report.append({'file':ktx.name,'sha256':hashlib.sha256(ktx.read_bytes()).hexdigest(),'sourceSha256':digest,'bytes':ktx.stat().st_size,'fallback':fp.name})
    lo,hi=image_map[digest];texture_map[tid]=len(textures);textures.append({'source':lo,'sampler':texture.get('sampler',0),'extensions':{'KHR_texture_basisu':{'source':hi}}})
for mat in doc['materials']:
    pbr=mat['pbrMetallicRoughness']
    if 'baseColorTexture' in pbr:pbr['baseColorTexture']['index']=texture_map[pbr['baseColorTexture']['index']]
    if 'normalTexture' in mat:mat['normalTexture']['index']=texture_map[mat['normalTexture']['index']]
doc['images']=images;doc['textures']=textures;doc.setdefault('extensionsUsed',[]).append('KHR_texture_basisu')
# Keep JPEG/PNG as a valid fallback if GPU texture compression is unavailable.
doc['extensionsRequired']=[x for x in doc.get('extensionsRequired',[]) if x!='KHR_texture_basisu']
if not doc['extensionsRequired']:doc.pop('extensionsRequired')
raw=(MODEL/doc['buffers'][0]['uri']).read_bytes();doc['buffers'][0].pop('uri');raw+=b'\0'*(-len(raw)%4)
doc['asset'].update(generator='Carlisle Coast / Quaternius CC0 modular city / stylized platformer presentation')
js=json.dumps(doc,separators=(',',':')).encode();js+=b' '*(-len(js)%4)
(OUT/'city.glb').write_bytes(struct.pack('<III',0x46546c67,2,28+len(js)+len(raw))+struct.pack('<II',len(js),0x4e4f534a)+js+struct.pack('<II',len(raw),0x004e4942)+raw)
shutil.copy(WORK/'manifest.json',OUT/'manifest.json');shutil.copy(WORK/'collision.json',ROOT/'src/cityShapes.json')
(TEX/'manifest.json').write_text(json.dumps(report,indent=2)+'\n')
models=json.loads((WORK/'manifest.json').read_text());labels={'cityroad2':'two-lane street','cityroad4':'four-lane boulevard','citycrossing':'city crossroads','citytjunction':'city T junction','citycurve2':'curved two-lane street','citycurve4':'curved boulevard','citytownhouse':'ornate townhouse','cityapartments':'city apartments','citycivic':'civic building','citybrickshops':'brick shop block','citywarehouse':'brick warehouse','citycreamoffice':'cream office block','cityglassoffice':'glass office block','cityterrace':'brick terrace','citysteelworks':'steel works block'}
lines=['// Generated by tools/carlisle-coast/pack_city.py from the fitted CC0 kit.','export const CITY_MODULES = {']
for m in models:
    m['label']=labels.get(m['kind'],m['label']);lines.append(m['kind']+':'+json.dumps(m,separators=(',',':'))+',')
lines.append('} as const;\nexport type CityKind=keyof typeof CITY_MODULES;\n')
(ROOT/'src/cityModules.ts').write_text('\n'.join(lines))
print('Packed',len(models),'models and',len(report),'shared albedos')
