// Start Vite, then: PLAYWRIGHT_MODULE=/path/to/playwright/index.mjs node tools/roo-type/bake.mjs
import fs from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const root=new URL('../../',import.meta.url);
const browser=await chromium.launch({headless:true,channel:'chrome'});
try {
  const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`${process.env.ROO_LAB_URL||'http://127.0.0.1:5178/'}roo-type-lab.html`);
  await page.waitForFunction(()=>window.rooTypeLab?.ready);
  await page.locator('#motion').uncheck();
  await page.evaluate(()=>window.rooTypeLab.setTime(0));
  const results=await page.evaluate(()=>window.rooTypeLab.bake());
  const metrics={};
  for(const result of results){
    const png=Buffer.from(result.png.split(',')[1],'base64');
    await fs.writeFile(new URL(`public/fonts/roo-${result.name}-v1.png`,root),png);
    await fs.writeFile(new URL(`public/fonts/roo-${result.name}-v1.json`,root),JSON.stringify(result.metrics,null,2)+'\n');
    metrics[result.name]=result.metrics;
    console.log(`${result.name}: ${result.metrics.width}×${result.metrics.height}, ${png.length} bytes, ${Object.keys(result.metrics.glyphs).length} glyphs`);
  }
  await fs.writeFile(new URL('src/roo-type/atlas-metrics.ts',root),`// Generated by tools/roo-type/bake.mjs; dimensions are cap-band units.\nimport type { RooAtlasMetrics } from './bake';\nexport const ROO_ATLAS_METRICS: Record<'bonus'|'counter',RooAtlasMetrics> = ${JSON.stringify(metrics)};\n`);
  if(errors.length)throw new Error(errors.join('\n'));
} finally { await browser.close(); }
