"""Install a visually reviewed full model-font bake; preserve source provenance.

This validates coverage/bytes, not visual fidelity. Run the browser review first.
"""
from pathlib import Path
import hashlib,json,shutil,zipfile

root=Path(__file__).resolve().parents[2]
art=root/'art/roo-reference-match'
bake=art/'bake'
report=json.loads((bake/'report.json').read_text())
assert report['errors']==[] and report['missing']==[]
assert len(report['provenance'])==51
font_hash=hashlib.sha256((root/'public/fonts/RooRegular.ttf').read_bytes()).hexdigest()
version=report['atlases']['bonus']['metrics']['version']
model_sources={}
history=json.loads((art/'review.json').read_text())
generated_dirs={Path(c['generatedSource']).parent for c in history['candidates'] if c.get('generatedSource')}
for generated in generated_dirs:
    if generated.exists():
        for p in generated.glob('exec-*.png'):
            model_sources[hashlib.sha256(p.read_bytes()).hexdigest()]=p.name
for recorded in sorted((root/'public/fonts').glob('roo-font-v*-provenance.json')):
    for item in json.loads(recorded.read_text())['glyphs'].values():
        model_sources.setdefault(item['modelSha256'],item['generatorOutput'])
provenance={'version':version,'font':'RooRegular.ttf','fontSha256':font_hash,'generator':'built-in image_gen',
            'generatorModel':None,'generatorQuality':None,
            'generatorControls':'The built-in tool did not expose or report a model ID or quality setting for the original passes.',
            'method':'Per-glyph model color/detail pass; analytic original Roo curve alpha; reference lighting retained where available; smooth floating-point color profile; three aligned bevel-light frames in two palettes.',
            'lighting':{'frames':['neutral','left','right'],'keyShift':[0,-.85,.85],'method':'Render the same Roo mesh and color field three times; change only bevel light; blend premultiplied pixels with identical alpha.'},
            'glyphCount':51,'glyphs':{}}
for char,item in report['provenance'].items():
    model=art/item['model'];prompt=art/item['prompt'];assert model.is_file()and prompt.is_file()
    digest=hashlib.sha256(model.read_bytes()).hexdigest()
    assert digest in model_sources,f'Unverified image-model output for {char}'
    provenance['glyphs'][char]={'model':item['model'],'modelSha256':digest,'generatorOutput':model_sources[digest],
        'prompt':item['prompt'],'promptText':prompt.read_text(),'reference':item.get('reference')}
    generation=next(c for c in history['candidates'] if c['file']==item['model'])
    if generation.get('inputs'):
        provenance['glyphs'][char]['inputs']=[{'file':p,'sha256':hashlib.sha256((art/p).read_bytes()).hexdigest()} for p in generation['inputs']]
metrics={}
for palette in ['bonus','counter']:
    metrics[palette]=json.loads((bake/f'roo-{palette}-v{version}.json').read_text())
    assert metrics[palette]['fontSha256']==font_hash
    assert len(metrics[palette]['glyphs'])==52
    for suffix in ['.json','.png','-light1.png','-light2.png']:
        name=f'roo-{palette}-v{version}{suffix}'
        shutil.copy2(bake/name,root/'public/fonts'/name)
(root/'src/roo-type/atlas-metrics.ts').write_text("// Generated by tools/roo-type/install-bake.py; dimensions are cap-band units.\nimport type { RooAtlasMetrics } from './bake';\nexport const ROO_ATLAS_METRICS: Record<'bonus'|'counter',RooAtlasMetrics> = "+json.dumps(metrics,separators=(',',':'))+';\n')
(root/f'public/fonts/roo-font-v{version}-provenance.json').write_text(json.dumps(provenance,indent=2)+'\n')
readme='''Roo reference image font v3

Every nonempty glyph has a separate, recorded built-in image_gen pass.
Original Roo contours provide the transparent alpha. The bake retains measured
reference light/color where available and adds the model's finer surface detail.
Three aligned lighting frames are supplied for each palette: neutral (no suffix),
-light1 (left) and -light2 (right). Geometry, crop rectangles and alpha match.
Crossfade their premultiplied RGBA with weights summing to 1 on an isolated
surface. Do not use ordinary source-over fading; it changes edge alpha.
The renderer defaults to a gentle 11-second cycle and respects reduced motion.

PNG cap band: 384 pixels. Use JSON crop rectangles, bearings, advances and kerning.
All placement values are in cap-band units. Multiply by the requested text size.
layouts.BONUS supplies the reference's per-letter optical placement.
Space has an advance and no bitmap. Both palettes have identical alpha masks.
The game's default extra tracking is -0.065 cap-band units. The Font Studio
spacing control saves a fork-owned preference shared by menus and HUD.
See roo-font-v3-provenance.json for all 51 source hashes and prompts.
The original built-in image tool did not expose model or quality controls;
these assets are not claimed to have been generated by a specific model tier.
'''
with zipfile.ZipFile(root/f'public/fonts/roo-image-font-v{version}.zip','w',zipfile.ZIP_DEFLATED,compresslevel=6)as archive:
    for palette in ['bonus','counter']:
        for suffix in ['.json','.png','-light1.png','-light2.png']:
            p=root/'public/fonts'/f'roo-{palette}-v{version}{suffix}';archive.write(p,p.name)
    archive.write(root/f'public/fonts/roo-font-v{version}-provenance.json',f'roo-font-v{version}-provenance.json')
    archive.writestr('README.txt',readme)
print(json.dumps({'installedGlyphs':51,'fontSha256':font_hash,'zip':str(root/f'public/fonts/roo-image-font-v{version}.zip')}))
