"""Install the reviewed v8 colours and glints; retain the approved orange neutral."""
from pathlib import Path
import hashlib,json,shutil,zipfile
from PIL import Image
import numpy as np

root=Path(__file__).resolve().parents[2];fonts=root/'public/fonts';bake=root/'art/roo-reference-match/bake'
digest=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
metrics={};inputs={}
for palette in ['bonus','counter']:
 m=json.loads((fonts/f'roo-{palette}-v6.json').read_text());m['version']=8;metrics[palette]=m
 for suffix in ['', '-light1','-light2']:
  source=fonts/f'roo-counter-v6{suffix}.png'
  candidate=source if palette=='counter' and not suffix else bake/f'roo-{palette}-v8{suffix}.png'
  original=np.asarray(Image.open(source).convert('RGBA'));graded=np.asarray(Image.open(candidate).convert('RGBA'))
  assert original.shape==graded.shape and np.array_equal(original[:,:,3],graded[:,:,3]),'Grade changed the approved glyph shape'
  shutil.copy2(candidate,fonts/f'roo-{palette}-v8{suffix}.png')
  inputs[source.name]=digest(source)
 (fonts/f'roo-{palette}-v8.json').write_text(json.dumps(m,indent=2)+'\n')
provenance=json.loads((fonts/'roo-font-v6-provenance.json').read_text());provenance['version']=8
provenance['lighting']['postprocess']='Newly lit, bright low-chroma pixels from each model glisten edit are strengthened while retaining the full neutral alpha. The orange neutral is unchanged.'
provenance['secondPalette']='Reference-calibrated lime/green to azure/cobalt hue, saturation and value from the approved gold artwork. Strong pigment is retained while green intensity matches the original reference; white model glints are protected. No spatial masks or geometry changes.'
provenance['paletteRevision']={'baseVersion':6,'sourceFrames':inputs,'neutralOrangeUnchanged':True,'script':'tools/roo-type/artwork-palette.ts','scriptSha256':digest(root/'tools/roo-type/artwork-palette.ts'),'function':'goldToBonusReference','highlightFunction':'enhanceModelGlisten','lightCycleSeconds':4.2, 'paletteReference':'art/roo-reference-match/analysis/BONUS-reference-native.png'}
(fonts/'roo-font-v8-provenance.json').write_text(json.dumps(provenance,indent=2)+'\n')
(root/'src/roo-type/atlas-metrics.ts').write_text("// Generated by tools/roo-type/install-refined-font.py; dimensions are cap-band units.\nimport type { RooAtlasMetrics } from './bake';\nexport const ROO_ATLAS_METRICS: Record<'bonus'|'counter',RooAtlasMetrics> = "+json.dumps(metrics,separators=(',',':'))+';\n')
with zipfile.ZipFile(fonts/'roo-image-font-v6.zip') as previous:readme=previous.read('README.txt').decode()
readme=readme.replace('image font v6','image font v8')+'\nV8 retains the approved orange neutral PNG byte-for-byte. Green/cobalt uses the\noriginal reference colour range, and model glints are strengthened, retaining\nall artwork detail and exact alpha. The full light cycle takes 4.2 seconds. Geometry and spacing are unchanged.\n'
with zipfile.ZipFile(fonts/'roo-image-font-v8.zip','w',zipfile.ZIP_DEFLATED,compresslevel=6) as archive:
 for palette in ['bonus','counter']:
  for suffix in ['.json','.png','-light1.png','-light2.png']:
   p=fonts/f'roo-{palette}-v8{suffix}';archive.write(p,p.name)
 archive.write(fonts/'roo-font-v8-provenance.json','roo-font-v8-provenance.json');archive.writestr('README.txt',readme)
print(json.dumps({'version':8,'glyphs':51,'neutralOrangeUnchanged':True,'identicalAlpha':True}))
