"""Install v10 without gamut chroma reduction; preserve all v9 orange frames."""
from pathlib import Path
import hashlib,json,shutil,zipfile
from PIL import Image
import numpy as np

root=Path(__file__).resolve().parents[2];fonts=root/'public/fonts';bake=root/'art/roo-reference-match/bake'
digest=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
metrics={};inputs={}
for palette in ['bonus','counter']:
 m=json.loads((fonts/f'roo-{palette}-v9.json').read_text());m['version']=10;metrics[palette]=m
 for suffix in ['', '-light1','-light2']:
  source=fonts/f'roo-counter-v6{suffix}.png'
  candidate=bake/f'roo-bonus-v10{suffix}.png' if palette=='bonus' else fonts/f'roo-counter-v9{suffix}.png'
  original=np.asarray(Image.open(source).convert('RGBA'));result=np.asarray(Image.open(candidate).convert('RGBA'))
  assert original.shape==result.shape and np.array_equal(original[:,:,3],result[:,:,3]),'Changed approved glyph alpha'
  shutil.copy2(candidate,fonts/f'roo-{palette}-v10{suffix}.png')
  inputs[source.name if palette=='bonus' else candidate.name]=digest(source if palette=='bonus' else candidate)
 (fonts/f'roo-{palette}-v10.json').write_text(json.dumps(m,indent=2)+'\n')
provenance=json.loads((fonts/'roo-font-v9-provenance.json').read_text());provenance['version']=10
provenance['lighting']['postprocess']='Green uses the original neutral and two model glisten frames, with no highlight amplification. All three orange frames are retained byte-for-byte from v9. All frame alpha remains fixed.'
provenance['secondPalette']='Earlier green/teal/cobalt hue curve with original source lightness and chroma before RGB encoding. No saturation multiplier, contrast curve, exposure gain, glint boost or gamut-driven chroma reduction. Out-of-range channels are bounded by the standard sRGB encoder; they are not desaturated to fit.'
provenance['paletteRevision']={'baseVersion':6,'hueVersion':7,'sourceFrames':inputs,'allOrangeFramesUnchanged':True,'script':'tools/roo-type/artwork-palette.ts','scriptSha256':digest(root/'tools/roo-type/artwork-palette.ts'),'function':'goldToBonusUncompressed','chromaScale':1,'faceLightness':[0,1],'exposureGain':1,'highlightGain':0,'gamutCompression':False,'gamutMapping':'Bound RGB channels at encoding; no chroma reduction.','lightCycleSeconds':4.2}
(fonts/'roo-font-v10-provenance.json').write_text(json.dumps(provenance,indent=2)+'\n')
(root/'src/roo-type/atlas-metrics.ts').write_text("// Generated by tools/roo-type/install-uncompressed-font.py; dimensions are cap-band units.\nimport type { RooAtlasMetrics } from './bake';\nexport const ROO_ATLAS_METRICS: Record<'bonus'|'counter',RooAtlasMetrics> = "+json.dumps(metrics,separators=(',',':'))+';\n')
with zipfile.ZipFile(fonts/'roo-image-font-v6.zip') as previous:readme=previous.read('README.txt').decode()
readme=readme.replace('image font v6','image font v10')+'\nV10 removes the remaining gamut-driven chroma reduction from green/teal/cobalt.\nHue conversion retains source lightness and chroma before standard RGB channel\nbounds. No saturation boost, contrast curve, exposure adjustment or glint gain.\nAll v9 orange frames, alpha, geometry and spacing are unchanged.\n'
with zipfile.ZipFile(fonts/'roo-image-font-v10.zip','w',zipfile.ZIP_DEFLATED,compresslevel=6) as archive:
 for palette in ['bonus','counter']:
  for suffix in ['.json','.png','-light1.png','-light2.png']:
   p=fonts/f'roo-{palette}-v10{suffix}';archive.write(p,p.name)
 archive.write(fonts/'roo-font-v10-provenance.json','roo-font-v10-provenance.json');archive.writestr('README.txt',readme)
print(json.dumps({'version':10,'glyphs':51,'allOrangeFramesUnchanged':True,'identicalAlpha':True}))
