"""Install a visually reviewed full model-font bake; preserve source provenance.

This validates coverage/bytes, not visual fidelity. Run the browser review first.
"""
from pathlib import Path
import hashlib,json,shutil,zipfile

root=Path(__file__).resolve().parents[2]
art=root/'art/roo-reference-match'
bake=art/'bake'
report=json.loads((bake/'report.json').read_text())
assert report['errors']==[] and report['missing']==[]
assert len(report['provenance'])==51
font_hash=hashlib.sha256((root/'public/fonts/RooRegular.ttf').read_bytes()).hexdigest()
model_sources={}
history=json.loads((art/'review.json').read_text())
generated_dirs={Path(c['generatedSource']).parent for c in history['candidates'] if c.get('generatedSource')}
for generated in generated_dirs:
    if generated.exists():
        for p in generated.glob('exec-*.png'):
            model_sources[hashlib.sha256(p.read_bytes()).hexdigest()]=p.name
recorded=root/'public/fonts/roo-font-v2-provenance.json'
if recorded.exists():
    for item in json.loads(recorded.read_text())['glyphs'].values():
        model_sources.setdefault(item['modelSha256'],item['generatorOutput'])
provenance={'version':2,'font':'RooRegular.ttf','fontSha256':font_hash,'generator':'built-in image_gen',
            'method':'Per-glyph model color/detail pass; original Roo geometry alpha; reference lighting/color retained where available; two baked palettes.',
            'glyphCount':51,'glyphs':{}}
for char,item in report['provenance'].items():
    model=art/item['model'];prompt=art/item['prompt'];assert model.is_file()and prompt.is_file()
    digest=hashlib.sha256(model.read_bytes()).hexdigest()
    assert digest in model_sources,f'Unverified image-model output for {char}'
    provenance['glyphs'][char]={'model':item['model'],'modelSha256':digest,'generatorOutput':model_sources[digest],
        'prompt':item['prompt'],'promptText':prompt.read_text(),'reference':item.get('reference')}
metrics={}
for palette in ['bonus','counter']:
    metrics[palette]=json.loads((bake/f'roo-{palette}-v2.json').read_text())
    assert metrics[palette]['fontSha256']==font_hash
    assert len(metrics[palette]['glyphs'])==52
    for ext in ['png','json']:
        shutil.copy2(bake/f'roo-{palette}-v2.{ext}',root/'public/fonts'/f'roo-{palette}-v2.{ext}')
(root/'src/roo-type/atlas-metrics.ts').write_text("// Generated by tools/roo-type/install-bake.py; dimensions are cap-band units.\nimport type { RooAtlasMetrics } from './bake';\nexport const ROO_ATLAS_METRICS: Record<'bonus'|'counter',RooAtlasMetrics> = "+json.dumps(metrics,separators=(',',':'))+';\n')
(root/'public/fonts/roo-font-v2-provenance.json').write_text(json.dumps(provenance,indent=2)+'\n')
readme='''Roo reference image font v2

Every nonempty glyph has a separate, recorded built-in image_gen pass.
Original Roo contours provide the transparent alpha. The bake retains measured
reference light/color where available and adds the model's finer surface detail.
This is a PNG font with fixed lighting, not a live relighting renderer.

PNG cap band: 384 pixels. Use JSON crop rectangles, bearings, advances and kerning.
All placement values are in cap-band units. Multiply by the requested text size.
layouts.BONUS supplies the reference's per-letter optical placement.
Space has an advance and no bitmap. Both palettes have identical alpha masks.
See roo-font-v2-provenance.json for all 51 source hashes and prompts.
'''
with zipfile.ZipFile(root/'public/fonts/roo-image-font-v2.zip','w',zipfile.ZIP_DEFLATED,compresslevel=6)as archive:
    for palette in ['bonus','counter']:
        for ext in ['png','json']:
            p=root/'public/fonts'/f'roo-{palette}-v2.{ext}';archive.write(p,p.name)
    archive.write(root/'public/fonts/roo-font-v2-provenance.json','roo-font-v2-provenance.json')
    archive.writestr('README.txt',readme)
print(json.dumps({'installedGlyphs':51,'fontSha256':font_hash,'zip':str(root/'public/fonts/roo-image-font-v2.zip')}))
