"""Install the reviewed v7 green grade; retain every approved orange byte."""
from pathlib import Path
import hashlib,json,shutil,zipfile
from PIL import Image
import numpy as np

root=Path(__file__).resolve().parents[2];fonts=root/'public/fonts';bake=root/'art/roo-reference-match/bake'
digest=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
metrics={};inputs={}
for palette in ['bonus','counter']:
 m=json.loads((fonts/f'roo-{palette}-v6.json').read_text());m['version']=7;metrics[palette]=m
 for suffix in ['', '-light1','-light2']:
  source=fonts/f'roo-counter-v6{suffix}.png'
  candidate=bake/f'roo-bonus-v7{suffix}.png' if palette=='bonus' else source
  original=np.asarray(Image.open(source).convert('RGBA'));graded=np.asarray(Image.open(candidate).convert('RGBA'))
  assert original.shape==graded.shape and np.array_equal(original[:,:,3],graded[:,:,3]),'Grade changed the approved glyph shape'
  shutil.copy2(candidate,fonts/f'roo-{palette}-v7{suffix}.png')
  inputs[source.name]=digest(source)
 (fonts/f'roo-{palette}-v7.json').write_text(json.dumps(m,indent=2)+'\n')
provenance=json.loads((fonts/'roo-font-v6-provenance.json').read_text());provenance['version']=7
provenance['secondPalette']='Pointwise Oklab grade from the approved gold frames: restrained chroma, compressed face lightness, smooth green/cobalt hue curve, bright neutral glint protection and chroma-only gamut mapping. Alpha and geometry are unchanged.'
provenance['paletteRevision']={'baseVersion':6,'sourceFrames':inputs,'orangeUnchanged':True,'script':'tools/roo-type/artwork-palette.ts','scriptSha256':digest(root/'tools/roo-type/artwork-palette.ts'),'function':'goldToBonusBalanced','chromaScale':.8,'faceLightness':[.12,.76],'colorSpaceReference':'https://bottosson.github.io/posts/oklab/'}
(fonts/'roo-font-v7-provenance.json').write_text(json.dumps(provenance,indent=2)+'\n')
(root/'src/roo-type/atlas-metrics.ts').write_text("// Generated by tools/roo-type/install-palette-bake.py; dimensions are cap-band units.\nimport type { RooAtlasMetrics } from './bake';\nexport const ROO_ATLAS_METRICS: Record<'bonus'|'counter',RooAtlasMetrics> = "+json.dumps(metrics,separators=(',',':'))+';\n')
with zipfile.ZipFile(fonts/'roo-image-font-v6.zip') as previous:readme=previous.read('README.txt').decode()
readme=readme.replace('image font v6','image font v7')+'\nV7 retains the approved orange PNGs byte-for-byte. Green/cobalt uses a softer\nperceptual color grade with reduced chroma and face contrast, while retaining\nbright glints, all artwork detail and exact alpha. Geometry and spacing are unchanged.\n'
with zipfile.ZipFile(fonts/'roo-image-font-v7.zip','w',zipfile.ZIP_DEFLATED,compresslevel=6) as archive:
 for palette in ['bonus','counter']:
  for suffix in ['.json','.png','-light1.png','-light2.png']:
   p=fonts/f'roo-{palette}-v7{suffix}';archive.write(p,p.name)
 archive.write(fonts/'roo-font-v7-provenance.json','roo-font-v7-provenance.json');archive.writestr('README.txt',readme)
print(json.dumps({'version':7,'glyphs':51,'orangeUnchanged':True,'identicalAlpha':True}))
