"""Install a complete, visually reviewed bitmap-owned Roo font bake."""
from pathlib import Path
import hashlib,json,shutil,zipfile

root=Path(__file__).resolve().parents[2]
art=root/'art/roo-reference-match';bake=art/'bake';fonts=root/'public/fonts'
report=json.loads((bake/'raster-report.json').read_text())
manifest=json.loads((art/'raster-v6/manifest.json').read_text())
prior=json.loads((fonts/'roo-font-v5-provenance.json').read_text())
assert report['errors']==[] and report['missing']==[] and report['missingLighting']==[]
assert len(report['provenance'])==len(manifest['glyphs'])==51
digest=lambda path:hashlib.sha256(Path(path).read_bytes()).hexdigest()
font_hash=digest(fonts/'RooRegular.ttf')
provenance={
 'version':6,'font':'RooRegular.ttf','fontSha256':font_hash,'glyphCount':51,
 'generator':'built-in image_gen','generatorModel':None,'generatorQuality':None,
 'generatorControls':'The built-in image tool did not expose or report a selectable model ID or quality tier.',
 'method':'Each complete model glyph supplies the finished face, bevel and silhouette. Preserve the actual artwork; remove only its separate flat matte and tiny detached contamination. No original-vector clipping or reprojection.',
 'lighting':{'frames':['neutral','left','right'],'method':'Two direct image-model glisten edits of each approved neutral, asking for highlights and shadows in different areas while preserving the finished letter. Register the complete images and composite source-atop the neutral bitmap to hold its complete shape and alpha. No inferred normals, reconstructed bevels, vector clipping or procedural relighting.','generationInput':'The already-generated approved neutral PNG is the sole image input.','bloom':'Near-white specular peaks are retained for later real-time bloom; no glow or halo is added by the bake.'},
 'secondPalette':'Pointwise hue grading retains saturation, value, alpha and the painted image detail. It does not create new lighting.',
 'glyphs':{}
}
def input_record(name):return {'file':name,'sha256':digest(art/name)}
for char,item in report['provenance'].items():
 master=manifest['glyphs'][char];assert master.get('model')==item['model']
 model=art/item['model'];sha=digest(model)
 generated=Path(master['generatedSource'])
 assert generated.is_file() and digest(generated)==sha,f'Unverified generator output for {char}'
 if master.get('modelSha256'):assert sha==master['modelSha256']
 if char=='0':
  inputs=prior['glyphs']['0']['inputs'];prompt=prior['glyphs']['0']['prompt']
  assert sha==prior['glyphs']['0']['modelSha256']
 else:
  inputs=[input_record(master['matteInput'])] if master.get('matteInput') else [input_record(master['input']),input_record(master['style'])]
  prompt=master['prompt']
 entry={'model':item['model'],'modelSha256':sha,'generatorOutput':generated.name,'prompt':prompt,'promptText':(art/prompt).read_text(),'inputs':inputs,
        'sourceBounds':item['sourceBounds'],'sourceBackground':item['background'],'contourSource':'model-artwork','components':item['components'],'glisten':{}}
 for side in ['left','right']:
  light=master['lightSources'][side];light_model=art/light['model'];light_sha=digest(light_model)
  assert light['neutralModel']==master['model']
  assert light_sha==light['modelSha256']==digest(light['generatedSource'])
  entry['glisten'][side]={'model':light['model'],'modelSha256':light_sha,'generatorOutput':Path(light['generatedSource']).name,'prompt':light['prompt'],'promptText':(art/light['prompt']).read_text(),'inputs':[input_record(master['model'])],'sourceBounds':item['lightBounds'][side]}
 if master.get('creationPrompt'):
  entry['creation']={'prompt':master['creationPrompt'],'promptText':(art/master['creationPrompt']).read_text(),'inputs':[input_record(master['input']),input_record(master['style'])],'output':input_record(master['matteInput'])}
 if char=='0':entry['reusedApprovedMasterFromVersion']=5
 provenance['glyphs'][char]=entry

metrics={}
for palette in ['bonus','counter']:
 m=json.loads((bake/f'roo-{palette}-v6.json').read_text())
 assert m['version']==6 and m['fontSha256']==font_hash and m['contourSource']=='model-artwork'
 assert len(m['glyphs'])==52 and m['lightFrames']==3
 metrics[palette]=m
 for suffix in ['.json','.png','-light1.png','-light2.png']:
  name=f'roo-{palette}-v6{suffix}';shutil.copy2(bake/name,fonts/name)
(fonts/'roo-font-v6-provenance.json').write_text(json.dumps(provenance,indent=2)+'\n')
(root/'src/roo-type/atlas-metrics.ts').write_text("// Generated by tools/roo-type/install-raster-bake.py; dimensions are cap-band units.\nimport type { RooAtlasMetrics } from './bake';\nexport const ROO_ATLAS_METRICS: Record<'bonus'|'counter',RooAtlasMetrics> = "+json.dumps(metrics,separators=(',',':'))+';\n')
readme='''Roo finished-artwork image font v6

51 nonempty glyphs and space. Both gold/vermilion and green/cobalt palettes.
Every selected glyph has an individual recorded built-in image-model pass;
the approved accented zero is reused from v5. Full painted bevels and actual
model contours are retained instead of clipping to the original flat vectors.

Each palette includes neutral, left (-light1) and right (-light2) PNG atlases.
The alternate highlights and shadows are direct image-model edits of the already-
approved neutral. The bake registers those images and holds the neutral bitmap's
complete shape; it does not infer normals or reconstruct/reshade the bevels.
Near-white glints are retained for real-time bloom later; no glow is baked in.
Blend premultiplied RGBA with weights summing to one on an isolated surface.
Do not use ordinary source-over fades, which change edge alpha.

Use JSON crop rectangles and cap-band metrics. Source cap band: 512 pixels.
The native aspect of the approved artwork is retained; cap size and baselines
remain shared. Default tracking is -0.065 cap units, adjustable in Font Studio.
Space has an advance and no bitmap. All palettes/frames share the same alpha.

Font Studio includes a moving light-position indicator, explicit paused/reduced-
motion states and a comparison of all three light angles. Appearance settings
are shared with the HUD and menus. See the provenance JSON for exact source
images, prompts and hashes. A selectable image-model ID/quality was not exposed.
'''
with zipfile.ZipFile(fonts/'roo-image-font-v6.zip','w',zipfile.ZIP_DEFLATED,compresslevel=6) as archive:
 for palette in ['bonus','counter']:
  for suffix in ['.json','.png','-light1.png','-light2.png']:
   path=fonts/f'roo-{palette}-v6{suffix}';archive.write(path,path.name)
 archive.write(fonts/'roo-font-v6-provenance.json','roo-font-v6-provenance.json')
 archive.writestr('README.txt',readme)
print(json.dumps({'version':6,'glyphs':51,'fontSha256':font_hash,'zip':str(fonts/'roo-image-font-v6.zip')}))
