"""Install v9 source-tone green; preserve all approved v8 orange frames."""
from pathlib import Path
import hashlib,json,shutil,zipfile
from PIL import Image
import numpy as np

root=Path(__file__).resolve().parents[2];fonts=root/'public/fonts';bake=root/'art/roo-reference-match/bake'
digest=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
metrics={};inputs={}
for palette in ['bonus','counter']:
 m=json.loads((fonts/f'roo-{palette}-v8.json').read_text());m['version']=9;metrics[palette]=m
 for suffix in ['', '-light1','-light2']:
  source=fonts/f'roo-counter-v6{suffix}.png'
  candidate=bake/f'roo-bonus-v9{suffix}.png' if palette=='bonus' else fonts/f'roo-counter-v8{suffix}.png'
  original=np.asarray(Image.open(source).convert('RGBA'));result=np.asarray(Image.open(candidate).convert('RGBA'))
  assert original.shape==result.shape and np.array_equal(original[:,:,3],result[:,:,3]),'Changed approved glyph alpha'
  shutil.copy2(candidate,fonts/f'roo-{palette}-v9{suffix}.png')
  inputs[source.name if palette=='bonus' else candidate.name]=digest(source if palette=='bonus' else candidate)
 (fonts/f'roo-{palette}-v9.json').write_text(json.dumps(m,indent=2)+'\n')
provenance=json.loads((fonts/'roo-font-v8-provenance.json').read_text());provenance['version']=9
provenance['lighting']['postprocess']='Green uses the original neutral and two model glisten frames, with no highlight amplification. All three orange frames are retained byte-for-byte from v8. All frame alpha remains fixed.'
provenance['secondPalette']='Earlier v7 green/teal/cobalt hue curve with the original artwork Oklab lightness and chroma. Removed face contrast compression, saturation scaling, v8 pigment remapping and green glint enhancement. Only out-of-gamut chroma is reduced to encode the hue-rotated colour in sRGB without clipping RGB channels.'
provenance['paletteRevision']={'baseVersion':6,'hueVersion':7,'sourceFrames':inputs,'allOrangeFramesUnchanged':True,'script':'tools/roo-type/artwork-palette.ts','scriptSha256':digest(root/'tools/roo-type/artwork-palette.ts'),'function':'goldToBonusNeutral','chromaScale':1,'faceLightness':[0,1],'highlightGain':0,'gamutMapping':'Reduce chroma only when required by sRGB; preserve lightness and hue.','lightCycleSeconds':4.2}
(fonts/'roo-font-v9-provenance.json').write_text(json.dumps(provenance,indent=2)+'\n')
(root/'src/roo-type/atlas-metrics.ts').write_text("// Generated by tools/roo-type/install-neutral-font.py; dimensions are cap-band units.\nimport type { RooAtlasMetrics } from './bake';\nexport const ROO_ATLAS_METRICS: Record<'bonus'|'counter',RooAtlasMetrics> = "+json.dumps(metrics,separators=(',',':'))+';\n')
with zipfile.ZipFile(fonts/'roo-image-font-v6.zip') as previous:readme=previous.read('README.txt').decode()
readme=readme.replace('image font v6','image font v9')+'\nV9 restores the earlier green/teal/cobalt hue curve with the original artwork\nlightness and chroma. No added contrast, saturation, exposure or green glint gain.\nAll v8 orange frames are unchanged. Alpha, geometry, spacing and the 4.2-second\nlight cycle are preserved. Gamut mapping prevents clipped RGB channels.\n'
with zipfile.ZipFile(fonts/'roo-image-font-v9.zip','w',zipfile.ZIP_DEFLATED,compresslevel=6) as archive:
 for palette in ['bonus','counter']:
  for suffix in ['.json','.png','-light1.png','-light2.png']:
   p=fonts/f'roo-{palette}-v9{suffix}';archive.write(p,p.name)
 archive.write(fonts/'roo-font-v9-provenance.json','roo-font-v9-provenance.json');archive.writestr('README.txt',readme)
print(json.dumps({'version':9,'glyphs':51,'allOrangeFramesUnchanged':True,'identicalAlpha':True}))
