// Generated by tools/jungle-kit/pack_modular.py from module-specs.json.
export const JUNGLE_MODULES = {
  stoneblock: {"file":"modular/ashlar-clean","label":"cut stone block","size":[2,1,1],"wind":false,"normalStrength":0.28,"lod":true,"doubleSided":false},
  wornstoneblock: {"file":"modular/ashlar","label":"worn stone block","size":[2,1,1],"wind":false,"normalStrength":0.28,"lod":true,"doubleSided":false},
  fracturedstoneblock: {"file":"modular/broken-ashlar","label":"fractured stone block","size":[2,1,1],"wind":false,"normalStrength":0.3,"lod":true,"doubleSided":false},
  stonepaver: {"file":"modular/paving-slab","label":"stone paving slab","size":[2,0.28,2],"wind":false,"normalStrength":0.24,"lod":true,"doubleSided":false},
  stonebase: {"file":"modular/column-base","label":"column base","size":[2.6,0.85,2.6],"wind":false,"normalStrength":0.28,"lod":true,"doubleSided":false},
  stoneshaft: {"file":"modular/column-shaft","label":"column shaft block","size":[1.65,1.8,1.65],"wind":false,"normalStrength":0.28,"lod":true,"doubleSided":false},
  stonecapital: {"file":"modular/column-capital","label":"column capital","size":[2.8,1.15,2.8],"wind":false,"normalStrength":0.26,"lod":true,"doubleSided":false},
  stonecornice: {"file":"modular/cornice","label":"straight cornice","size":[3,0.75,1.15],"wind":false,"normalStrength":0.24,"lod":true,"doubleSided":false},
  stonecorner: {"file":"modular/corner-cornice","label":"corner cornice","size":[3,0.75,3],"wind":false,"normalStrength":0.24,"lod":true,"doubleSided":false},
  stonelintel: {"file":"modular/lintel","label":"carved lintel","size":[4,1,1.1],"wind":false,"normalStrength":0.32,"lod":true,"doubleSided":false},
  stonefrieze: {"file":"modular/carved-block","label":"spiral relief block","size":[2,1.5,1],"wind":false,"normalStrength":0.32,"lod":true,"doubleSided":false},
  stoneroof: {"file":"modular/roof-wedge","label":"sloping roof block","size":[2,1.1,2],"wind":false,"normalStrength":0.24,"lod":true,"doubleSided":true},
  stoneridge: {"file":"modular/ridge-cap","label":"roof ridge block","size":[2,0.65,0.85],"wind":false,"normalStrength":0.22,"lod":true,"doubleSided":false},
  stonearch: {"file":"modular/arch-stone","label":"arch wedge stone","size":[1.4,1.2,1.2],"wind":false,"normalStrength":0.22,"lod":true,"doubleSided":false},
  stonestep: {"file":"modular/temple-stair","label":"stone stair tread","size":[3,0.45,1.05],"wind":false,"normalStrength":0.22,"lod":true,"doubleSided":false},
  stonehip: {"file":"modular/roof-hip","label":"hip roof corner","size":[2,1.1,2],"wind":false,"normalStrength":0.24,"lod":true,"doubleSided":true},
  junglecanopy: {"file":"modular/canopy-tree","label":"jungle canopy tree","size":[15,14,13.5],"wind":true,"normalStrength":0.12,"lod":true,"doubleSided":false},
} as const;
export type JungleModuleKind = keyof typeof JUNGLE_MODULES;
export const JUNGLE_MODULE_KINDS = Object.keys(JUNGLE_MODULES) as JungleModuleKind[];
