// Generated by tools/jungle-kit/pack_editor_assets.py.
export const JUNGLE_EDITOR_ASSETS = {
  claybrick: {"file":"editor/clay-brick","label":"smooth clay brick","size":[2,1,1],"wind":false,"normalStrength":0.2,"lod":true},
  wornclaybrick: {"file":"editor/worn-clay-brick","label":"worn clay brick","size":[2,1,1],"wind":false,"normalStrength":0.2,"lod":true},
  fracturedclaybrick: {"file":"editor/fractured-clay-brick","label":"fractured clay brick","size":[2,1,1],"wind":false,"normalStrength":0.2,"lod":true},
  claypaver: {"file":"editor/clay-paver","label":"clay paving slab","size":[2,0.28,2],"wind":false,"normalStrength":0.2,"lod":true},
  agedclaybrick: {"file":"editor/aged-clay-brick","label":"aged earthen brick","size":[2,1,1],"wind":false,"normalStrength":0.2,"lod":true},
} as const;
