import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=fileURLToPath(new URL('./proof/',import.meta.url));await mkdir(out,{recursive:true});
const html=`<!doctype html><html><head><link rel="icon" href="data:,"><style>body{margin:0}</style><script type="importmap">{"imports":{"three":"/three/build/three.module.js"}}</script></head><body><script type="module">
import * as THREE from 'three';import {GLTFLoader} from '/three/examples/jsm/loaders/GLTFLoader.js';const params=new URLSearchParams(location.search),name=params.get('name'),angle=+params.get('angle')||0;
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(384,384);renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.append(renderer.domElement);const scene=new THREE.Scene();scene.background=new THREE.Color('#21182b');scene.add(new THREE.HemisphereLight(0xe9dcff,0x453935,2));const key=new THREE.DirectionalLight(0xffe3b3,3);key.position.set(-2,4,4);scene.add(key);const fill=new THREE.DirectionalLight(0x9bbcff,2);fill.position.set(2,3,-3);scene.add(fill);const model=(await new GLTFLoader().loadAsync('/assets/'+name+'.glb')).scene;scene.add(model);const box=new THREE.Box3().setFromObject(model),centre=box.getCenter(new THREE.Vector3());const camera=new THREE.PerspectiveCamera(35,1,.01,30),a=angle*Math.PI/180;
camera.position.set(Math.sin(a)*2.1,centre.y+.45,Math.cos(a)*2.1);if(name.includes('flagstone'))camera.position.set(.8,1.75,1.8);camera.lookAt(centre);renderer.render(scene,camera);window.proofReady=true;
</script></body></html>`;
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1');let body;if(url.pathname==='/')body=Buffer.from(html);else if(url.pathname.startsWith('/three/'))body=await readFile(root+'/node_modules'+url.pathname);else if(url.pathname.startsWith('/assets/'))body=await readFile(root+'/public/ghost-train/'+url.pathname.slice(8));else{res.writeHead(404);res.end();return;}res.setHeader('Content-Type',url.pathname==='/'?'text/html':url.pathname.endsWith('.glb')?'model/gltf-binary':'text/javascript');res.end(body);}catch(error){res.writeHead(404);res.end();}});
await new Promise(resolve=>server.listen(5269,'127.0.0.1',resolve));const {chromium}=await import('/Users/kiki/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');const browser=await chromium.launch({headless:true,channel:'chrome'}),errors=[];
try{const page=await browser.newPage({viewport:{width:384,height:384}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const specs=JSON.parse(await readFile(new URL('./prompts.json',import.meta.url),'utf8'));for(const name of process.argv.slice(2).length?process.argv.slice(2):Object.keys(specs)){for(const angle of ['castle-clockwork-v2','castle-wall-window-v2'].includes(name)?[0,90,180,270]:[35]){await page.goto('http://127.0.0.1:5269/?name='+name+'&angle='+angle);await page.waitForFunction(()=>window.proofReady);await page.screenshot({path:out+name+'-packed-'+angle+'.png'});}}console.log(JSON.stringify({errors,out}));}finally{await browser.close();server.close();}
